version: "3.9"

services:
  castlemock:
    image: tomcat:11.0.8-jdk21-temurin
    container_name: castlemock
    ports:
      - "8080:8080"
    volumes:
      - ./deploy/castlemock-v1.68.war:/usr/local/tomcat/webapps/castlemock.war:ro

#services:
#  castlemock:
#    image: yalcinyildiz/castlemock:v1.68
#    ports:
#      - "8080:8080"
